-- Personal Neovim config ("999rpm" — see utils.lua's augroup() note for where that name shows
-- up inside the config itself: every custom augroup is namespaced "999rpm-<name>").
--
-- Substantially adapted from jdhao/nvim-config <https://github.com/jdhao/nvim-config> — the
-- LSP/diagnostics setup (plugins/lsp/lspconfig.lua), several editor-behavior utilities
-- (utils.lua), and the general options/autocmds shape (config/options.lua, config/
-- autocmds.lua) all started from his config and are periodically diffed against his live repo
-- (see each file's own header for specifics). mason.lua is this config's own addition — jdhao
-- manages LSP/tool binaries by hand rather than through mason-lspconfig/mason-tool-installer.
--
-- A handful of smaller, specific pieces come from three other public configs, credited at the
-- point they're used rather than here, since each is a targeted addition, not a shape this
-- whole config follows the way it follows jdhao's:
--   • craftzdog/dotfiles-public <https://github.com/craftzdog/dotfiles-public> — an inlay-hint
--     tweak in lspconfig.lua.
--   • xero/dotfiles <https://github.com/xero/dotfiles> — the schemastore.nvim integration in
--     lspconfig.lua.
--   • rafi/vim-config <https://github.com/rafi/vim-config> — the context-menu (MenuPopup)
--     block in config/autocmds.lua, and plugins/ui/ufo.lua's provider_selector (the
--     lsp->treesitter->indent chain with proper UfoFallbackException handling, plus the
--     per-filetype exclusions).
--
-- File layout:
--   init.lua (this file)
--   └─ lua/
--      ├─ utils.lua              — shared helpers (git info, LSP capabilities, augroup naming)
--      ├─ config/                — editor behavior + the plugin manager itself
--      │  ├─ options.lua, autocmds.lua, mappings.lua, lazy.lua
--      └─ plugins/                — one file per plugin, auto-imported by lazy.lua
--         plugins/init.lua explicitly imports each category folder below by name (`{ import =
--         "plugins.lsp" }`, etc.) — lazy.nvim's own module discovery (lazy/core/util.lua's
--         lsmod) only scans one directory level at a time and won't descend into a category
--         folder on its own unless that folder has its own init.lua, which none of them do by
--         design (confirmed by reading lazy.nvim's source directly). Add a category folder
--         without adding it to plugins/init.lua and every spec inside it silently never loads.
--         ├─ lsp/          — lspconfig, mason, lazydev
--         ├─ completion/   — blink, copilot, autopairs
--         ├─ editor/       — flash, harpoon, surround, comment, textobjects, better-escape,
--         │                  ts-autotag, mini (mini.ai only), todo-comments
--         ├─ treesitter/   — treesitter, context, rainbow-delimiters
--         ├─ ui/           — alpha, bufferline, lualine, noice, notify, themes, which-key,
--         │                  web-devicons, statuscol, ufo, snacks,
--         │                  render-markdown, trouble, colorizer, bufdelete, float-backdrop
--         ├─ git/          — gitsigns, diffview
--         ├─ explorer/     — neo-tree, oil
--         ├─ search/       — telescope, fzf
--         ├─ debug/        — dap, dap-ui, dap-python, dap-virtual-text
--         ├─ test/         — neotest
--         ├─ lang-tools/   — conform, lint
--         └─ terminal/     — toggleterm
--
-- Feature overview (see each plugin's own file for details/keymaps):
--   • LSP + diagnostics  — nvim-lspconfig w/ schemastore.nvim, Mason-managed servers
--     (basedpyright+ruff, ts_ls, gopls, rust_analyzer, lua_ls, hls for Haskell, and more),
--     Trouble for diagnostics/symbols views
--   • Completion          — blink.cmp (LSP/path/snippets/buffer + lazydev for Lua), Copilot
--   • Fuzzy finding       — Telescope (files/grep/LSP pickers/help/keymaps/…) + fzf-lua for
--     a handful of fast common lookups
--   • File navigation     — neo-tree (tree explorer), oil.nvim (directory-as-buffer), Harpoon
--     (pin & jump between a handful of files), Flash (labelled jump/treesitter motions)
--   • Git                 — gitsigns (hunks/blame), Diffview (full diff/history views),
--     LazyGit + "open in browser" via snacks.nvim
--   • Debugging & testing — nvim-dap + nvim-dap-ui + dap-virtual-text + nvim-dap-python +
--     Haskell (haskell-debug-adapter), neotest (Jest adapter)
--   • Treesitter          — highlighting, incremental parsing, textobjects, sticky context
--     header, rainbow delimiters, auto tag close/rename, folding via nvim-ufo
--   • Formatting & linting— conform.nvim (format-on-save, per-filetype — the sole owner of
--     that job, see plugins/lsp/lspconfig.lua's note on why LSP-driven format-on-save doesn't
--     also live there), nvim-lint
--   • UI                  — bufferline + lualine (matching skewed/slant separators), which-key,
--     Noice (cmdline/messages, paired with notify.lua), alpha (start screen), a multi-theme
--     switcher (tokyonight/catppuccin/kanagawa), animated box-drawing indent/scope guides
--     (snacks.indent's chunk mode), a color-literal highlighter (nvim-colorizer.lua), a
--     dimmed backdrop behind Telescope/floating-terminal popups, a right-click context menu
--     (config/autocmds.lua's MenuPopup block)
--   • Editing QoL         — nvim-surround, Comment.nvim, autopairs, better-escape, mini.ai,
--     todo-comments, bufdelete.nvim (buffer close without disturbing window layout)
--   • Misc                — toggleterm (float/split terminal + a btop monitor), render-markdown
--
-- Full change history, and the reasoning behind decisions that aren't obvious from reading the
-- code alone, lives in AUDIT_SUMMARY.md — not here and not scattered across individual file
-- headers, so there's exactly one place to check before making a change and exactly one place
-- to update after making one.
if vim.loader then
	vim.loader.enable()
end

require("config.autocmds")
require("config.options")
require("config.mappings")
require("config.lazy")
